### PR TITLE
feat: add template sample to test app

### PR DESCRIPTION
**Pull request by gsilvapt**
As an example, because there is no theme configured here and this will have no impact in the app. **However**, another change to the project `README` is incoming after this change is merged to include a screenshot with an example of the template provided working with `django-surface-theme`.

### CODE REVIEW

**Review by fopina — DISMISSED** [review]

**Comment by gsilvapt** [comment]
In [that case](#11), perhaps we should close this one too, @fopina?

**Comment by fopina** [comment]
I think this one makes sense.

for apitokens to be used/demoed in the testapp, it needs to be made available

**Comment by fopina** [comment]
I just noticed this is using `navigation.html` which does not exist in django-admin default template.

I meant that I think this makes perfect sense but applied to the core template 😄

**Comment by fopina** [comment]
https://github.com/django/django/blob/main/django/contrib/admin/templates/admin/base.html#L46 block userlinks

**Comment by fopina** [comment]
pushed suggestion (navigation.html to be deleted).

image

Not the best look adding it after `Log out` but it was to avoid re-defining the entire block so it's easier to maintain. Options being before _view site_ or after _log out_ 🤷

**Comment by gsilvapt** [comment]
LGTM, we can keep it like that 👍 `testapp` is merely for demonstration purposes, so I'm okay with this change. Thus I thought about adding the instructions to add the API Tokens part to the `django-surface-theme` instead of here - but again, I think it's a fine change anyway 👌

**Review by fopina — APPROVED** [review]

**Pull request merged**
